name: Push Changes to GitHub and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Deploy to the production server via SSH
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 21098
        script: |
          cd /home/xurislrm/public_html
          # Ensure the directory exists
          mkdir -p public/build
          # Clear old build files if necessary
          rm -rf public/build/*
          # Copy the new build from the repository to the server
          scp -r ./public/build/* user@host:/home/xurislrm/public_html/public/build
